### ISSUE TITLE
关于部署到托管平台怎么更新内容呢？

### ISSUE THREAD

**Issue by ldpc520** [MadisonWirtanen/OneNav#1]
如题，把代码部署到了netlify托管平台上面，请问怎么进行内容的修改？

**Comment by MadisonWirtanen** [comment]
netlify在导入的时候Build Settings下面可以设置Branch to deploy，就是导入的分支，这里选择gh-pages分支即可，然后再修改fork仓库里master分支下的links.yml，GitHub Actions会自动生成修改后的网页文件并推送到gh-pages，netlify导入时是基于gh-pages分支的，就会自动修改了
