### ISSUE TITLE
左侧边栏怎么实现打开默认就是宽的？

### ISSUE THREAD

**Issue by ldpc520** [MadisonWirtanen/OneNav#3]
按说明尝试了把这些代码都删掉或只删一个都不行哦。能具体说下吗？
![11](https://github.com/user-attachments/assets/096bb6cf-7fb2-448e-8bdc-bcbaecbd37a3)
![2](https://github.com/user-attachments/assets/274361a6-202d-4764-936e-16067aa23589)

**Comment by MadisonWirtanen** [comment]
这个是在index.hbs文件里修改，而不是style.css
