### ISSUE TITLE
各link的logo没有生效，并且页面有大量报错

### ISSUE THREAD

**Issue by horizon365** [MadisonWirtanen/OneNav#4]
![image](https://github.com/user-attachments/assets/f6e255b1-877a-4b75-996e-bccf5eb256df)
所有Link的logo都成了同一个。

**Comment by MadisonWirtanen** [comment]
系网络问题，此网址仅作展示，可自行替换各元素

**Comment by horizon365** [comment]
感谢回复。我没太明白，例如 logo: https://cdn.imkk.uk/icon/svg/Home.svg  这个链接是有效的，为什么本地部署后也不能展示这个logo?

**Comment by MadisonWirtanen** [comment]
应该是重定向的原因吧，这个域名准备弃用了，已设置为重定向至新域名。

**Comment by horizon365** [comment]
![image](https://github.com/user-attachments/assets/c034f46c-92bd-4931-8bab-78e7c3b323ea)
然后还有这个报错，求解答

**Comment by MadisonWirtanen** [comment]
ChatGPT：
图中的报错主要是由于 jQuery 没有正确加载，导致其他依赖 jQuery 的脚本无法正常运行。具体问题如下：

1. **Uncaught Error: Bootstrap's JavaScript requires jQuery** - Bootstrap 的 JavaScript 文件依赖于 jQuery，但页面中未加载或未正确加载 jQuery。

2. **Uncaught ReferenceError: jQuery is not defined** - 这是因为 jQuery 未定义，导致在 `resizeable.min.js`、`xenon-toggles.min.js`、`xenon-custom.min.js` 等脚本中无法引用 jQuery。

3. **Uncaught TypeError: e is not a function** - 可能是因为某个函数调用依赖于 jQuery，但由于 jQuery 未加载，导致 `e` 被解释为非函数。

4. **Uncaught ReferenceError: $ is not defined** - jQuery 的简写符号 `$` 也未定义，通常表明 jQuery 没有加载成功。

### 解决方法
1. **确保 jQuery 在所有其他脚本之前加载** - 你需要在 HTML 中确保 `<script src="path/to/jquery.js"></script>` 出现在其他依赖 jQuery 的脚本之前。

2. **检查 jQuery 文件路径** - 确认 jQuery 文件路径正确且可访问。

3. **使用 CDN** - 若本地 jQuery 文件不可用，可以尝试使用 CDN，如：
   ```html
   <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
   ```

4. **检查脚本加载顺序** - 在引入 Bootstrap、`resizeable.min.js` 等文件之前引入 jQuery，以确保它们能找到 jQuery 依赖。

**Comment by horizon365** [comment]
感谢，我也问了GPT，最终确定是受我浏览器插件的影响，换个浏览器就好了。
可以关单了。
